# Generated by Django 3.0.8 on 2020-07-28 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('raca', models.CharField(choices=[('LAB', 'Labrador'), ('BUL', 'Buldogue'), ('POO', 'Poodle'), ('PAS', 'Pastor Alemão'), ('BEA', 'Beagle'), ('GOL', 'Golden Retriever'), ('CHI', 'Chihuahua'), ('HUS', 'Husky Siberiano')], max_length=3)),
                ('idade', models.IntegerField()),
            ],
        ),
    ]
